package travel_policy

# Generated by Stage 9: DSL to Rego Converter
# Date: 2026-02-05T12:35:26.831425
# This file contains all policy rules converted from DSL format



# Rule: C1
# Intent: LIMIT
# Ambiguous: False
allow_c1_limit {
    input.travelregion == "India"
    input.travelpurpose == "official business travel"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C10
# Intent: LIMIT
# Ambiguous: False
allow_c10_limit {
    input.gradem1lodgingcategorya == "Rs. 4000"
    input.gradem1lodgingcategoryb == "Rs. 3000"
    input.boardingallowance == "Actual"
    input.personalincidentalallowancelimit == "Rs. 150"
    input.personalincidentalallowance == "Actual"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C11
# Intent: LIMIT
# Ambiguous: False
allow_c11_limit {
    input.gradem2lodgingcategorya == "Rs. 3000"
    input.gradem2lodgingcategoryb == "Rs. 2000"
    input.boardingallowance == "Actual"
    input.personalincidentalallowancelimit == "Rs. 125"
    input.personalincidentalallowance == "Actual"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C12
# Intent: LIMIT
# Ambiguous: False
allow_c12_limit {
    input.gradem3lodgingcategorya == "Rs. 3000"
    input.gradem3lodgingcategoryb == "Rs. 2000"
    input.boardingallowance == "Actual"
    input.personalincidentalallowancelimit == "Rs. 100"
    input.personalincidentalallowance == "Actual"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C13
# Intent: LIMIT
# Ambiguous: False
allow_c13_limit {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C14
# Intent: LIMIT
# Ambiguous: False
allow_c14_limit {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C15
# Intent: LIMIT
# Ambiguous: False
allow_c15_limit {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C16
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c16_conditiona {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C17
# Intent: INFORMATIONAL
# Ambiguous: False
allow_c17_informatio {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "PASS",
        "status": "OK"
    }
}

# Rule: C18
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c18_conditiona {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C19
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c19_conditiona {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C2
# Intent: INFORMATIONAL
# Ambiguous: False
allow_c2_informatio {
    input.tourdurationmindays == 1
    input.tourdurationmaxdays == 15
    input.deputationdurationmindays == 15
    input.deputationdurationmaxdays == "1 year"
    input.transferdurationexceeds == "1 year"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "PASS",
        "status": "OK"
    }
}

# Rule: C20
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c20_conditiona {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C21
# Intent: RESTRICTION
# Ambiguous: False
allow_c21_restrictio {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "approval.required",
        "status": "YES"
    }
}

# Rule: C22
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c22_conditiona {
    input.minimumtravelduration >= "15 days"
    input.maximumtravelduration <= "1 year"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C23
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c23_conditiona {
    input.traveldurationrange == "1-7 days"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C24
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c24_conditiona {
    input.deputationdurationthreshold == "7 days"
    input.allowancesource == "Table 7"
    input.allowancedependency == "employee Grade and Category"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C25
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c25_conditiona {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C26
# Intent: RESTRICTION
# Ambiguous: False
allow_c26_restrictio {
    input.billsubmissionrequirement == "not required"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "approval.required",
        "status": "YES"
    }
}

# Rule: C27
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c27_conditiona {
    input.durationprojectionthreshold == "1 year"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C28
# Intent: LIMIT
# Ambiguous: False
allow_c28_limit {
    input.minimumreimbursementdistance >= "100 KM"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C29
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c29_conditiona {
    input.relocationduration == "7 days"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C3
# Intent: LIMIT
# Ambiguous: False
allow_c3_limit {
    input.allowancetype == "Lodging & Boarding"
    input.tourlocation == "India"
    input.ratesource == "Table 4"
    input.ratelimitation == "maximum permissible"
    input.billrequirement == "actual bills"
    input.taxinclusion == "exclusive of taxes"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.allowance_limit",
        "status": "STRICT"
    }
}

# Rule: C30
# Intent: INFORMATIONAL
# Ambiguous: False
allow_c30_informatio {
    input.gradem1lodgingallowance == "Actual"
    input.gradem1boardingallowance == "Actual"
    input.gradem1travelallowance == "Actual"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "PASS",
        "status": "OK"
    }
}

# Rule: C31
# Intent: LIMIT
# Ambiguous: False
allow_c31_limit {
    input.gradem2lodgingallowance == 4000
    input.gradem2boardingallowance == 350
    input.gradem2travelallowance == 150
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.lodging",
        "status": "STRICT"
    }
}

# Rule: C32
# Intent: LIMIT
# Ambiguous: False
allow_c32_limit {
    input.gradem2blodgingallowance == 3000
    input.gradem2bboardingallowance == 250
    input.gradem2btravelallowance == 125
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.lodging",
        "status": "STRICT"
    }
}

# Rule: C33
# Intent: LIMIT
# Ambiguous: False
allow_c33_limit {
    input.lodgingallowance == 2000
    input.boardingallowance == 150
    input.travelallowance == 100
    input.applicablegrades == "M3 to M6"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.allowance_limit",
        "status": "STRICT"
    }
}

# Rule: C34
# Intent: LIMIT
# Ambiguous: False
allow_c34_limit {
    input.referencetable == "Table 4"
    input.ratetype == "maximum permissible rates"
    input.billrequirement == "actual bills"
    input.taxinclusion == "exclusive of taxes"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C35
# Intent: RESTRICTION
# Ambiguous: False
allow_c35_restrictio {
    input.requireddocumentation == "bills/invoices"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "approval.required",
        "status": "YES"
    }
}

# Rule: C36
# Intent: APPROVAL_REQUIRED
# Ambiguous: False
allow_c36_approval_r {
    input.requiredquotations == 3
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C37
# Intent: LIMIT
# Ambiguous: False
allow_c37_limit {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C38
# Intent: LIMIT
# Ambiguous: False
allow_c38_limit {
    input.employeegrades == "M1/M2"
    input.travelmode == "Air (Economy)"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C39
# Intent: LIMIT
# Ambiguous: False
allow_c39_limit {
    input.employeegrade == "M2B"
    input.travelmode == "Train (AC II) /Taxi (AC)"
    input.taxirate == "10 Rs/KM"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C4
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c4_conditiona {
    input.eligiblegrades == "M1"
    input.airtravelclass == "Economy"
    input.traintravelclasses == "AC I, II"
    input.taxitravelclass == "AC"
    input.intercitytravelmodes == "Air, Train, Taxi"
    input.localtravelmodes == "Taxi"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C40
# Intent: LIMIT
# Ambiguous: False
allow_c40_limit {
    input.employeegrade == "M3"
    input.travelmodes == "Train (III AC) /Bus/Taxi(AC)"
    input.taxiactype == "AC"
    input.rateperkm == "10 Rs/KM"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C41
# Intent: INFORMATIONAL
# Ambiguous: False
allow_c41_informatio {
    input.employeegrade == "M4"
    input.allowedtravelmodes == "Train (III AC)/Bus(AC) /Shared Taxi/Auto"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "PASS",
        "status": "OK"
    }
}

# Rule: C42
# Intent: INFORMATIONAL
# Ambiguous: False
allow_c42_informatio {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "PASS",
        "status": "OK"
    }
}

# Rule: C43
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c43_conditiona {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C44
# Intent: APPROVAL_REQUIRED
# Ambiguous: False
allow_c44_approval_r {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C45
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c45_conditiona {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C46
# Intent: RESTRICTION
# Ambiguous: False
allow_c46_restrictio {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "approval.required",
        "status": "YES"
    }
}

# Rule: C47
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c47_conditiona {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C48
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c48_conditiona {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C49
# Intent: RESTRICTION
# Ambiguous: False
allow_c49_restrictio {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "approval.required",
        "status": "YES"
    }
}

# Rule: C5
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c5_conditiona {
    input.eligiblegrades == "M2"
    input.airtravelclass == "Economy"
    input.traintravelclasses == "AC I, II"
    input.taxitravelclass == "AC"
    input.taxicartypes == "hatchback/sedan"
    input.clienttravelcartypes == "Sedan/SUV"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C50
# Intent: RESTRICTION
# Ambiguous: False
allow_c50_restrictio {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "approval.required",
        "status": "YES"
    }
}

# Rule: C51
# Intent: RESTRICTION
# Ambiguous: False
allow_c51_restrictio {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "approval.required",
        "status": "YES"
    }
}

# Rule: C52
# Intent: APPROVAL_REQUIRED
# Ambiguous: False
allow_c52_approval_r {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C53
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c53_conditiona {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C54
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c54_conditiona {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C55
# Intent: ADVISORY
# Ambiguous: False
allow_c55_advisory {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C56
# Intent: RESTRICTION
# Ambiguous: False
allow_c56_restrictio {
    true
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "approval.required",
        "status": "YES"
    }
}

# Rule: C6
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c6_conditiona {
    input.eligibledesignations == "AGM, Sr. Manager, Sr. BM, RSM, Manager, Deputy Manager, Assistant Manager, Sr. Executive, Sr. Engineer, ASM, and BM (Grade M3)"
    input.intercitytravelmode == "Train (III AC) / Bus / Taxi (AC)"
    input.localtravelmode == "Taxi (AC)"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C7
# Intent: CONDITIONAL_ALLOWANCE
# Ambiguous: False
allow_c7_conditiona {
    input.eligibleemployeegrades == "M4"
    input.intercitytravelmodes == "Train (III AC) / Bus / Taxi (AC)"
    input.localtravelmodes == "Auto, Taxi (Non-AC)"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "allowance.general",
        "status": "CONDITIONAL"
    }
}

# Rule: C8
# Intent: LIMIT
# Ambiguous: False
allow_c8_limit {
    input.localautotravellimit == "<10 KM"
    input.intercitytravelmodes == "Train & Bus (Sleeper) / Shared Taxi / Auto"
    input.localtravelmodes == "Auto, Taxi (Non-AC)"
    input.over10kmtransport == "Public/Shared Transport"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Rule: C9
# Intent: LIMIT
# Ambiguous: False
allow_c9_limit {
    input.nonactaxirate == "Rs. 8/KM"
    input.actaxirate == "Rs. 10/KM"
    result := {
        "allow": true,
        "action": "enforce",
        "constraint": "limit.general",
        "status": "STRICT"
    }
}

# Default: Allow if no violations
allow_default {
    true
}
